name: GitHub - Activity - Readme

on:
  schedule:
     - cron: "0 * * * *"
   # - cron: "19 27 12 *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
