name: GitHub - Activity - Readme

on:
  schedule:
     - cron: "0 * * * *"
   # - cron: "19 27 12 *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     # - uses: Readme-Workflows/recent-activity@v2.3.1
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
